# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  name: null
  save_dir: "${paths.output_dir}"
  offline: False
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "Neural-P3M"
  log_model: False # upload lightning ckpts
  prefix: "" # a string to put at the beginning of metric keys
  group: ""
  tags: []
  job_type: ""
